In [2]:

import os
import joblib
import cv2
randomforest = joblib.load('RandomForestClassifier(15).pkl')
characterDict = {
    'agaPing':'아자핑',
 'banglePing':'방글핑',
 'baroPing':'바로핑',
 'chachaPing':'차차핑',
 'ggraePing':'꾸래핑',
 'hachuPing':'하츄핑',
 'happyPing':'해핑',
 'joaPing':'조아핑',
 'lalaPing':'라라핑',
 'malangPing':'말랑핑',
 'nanaPing':'나나핑',
 'posilPing':'포실핑',
 'soljjiPing':'솔찌핑',
 'trustPing':'믿어핑'
}

In [6]:
imgData = cv2.imread(r"test_image\test (1).jpg")
imgData = cv2.resize(imgData,(200,200))[:,:,:3].reshape((1,-1))/255.0

In [8]:
randomforest.predict(imgData)[0]

'nanaPing'

In [1]:
from keras.saving import load_model
import numpy as  np
model1='cnn_fashion_model_AGE.hdf5'
myModel = load_model(model1) # h5 보단 keras 확장자로 불러올 것


c:\Users\KDP19\anaconda3\envs\mypython\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\KDP19\anaconda3\envs\mypython\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\KDP19\anaconda3\envs\mypython\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [53]:
arr = np.array([[10**7,10,10**7.4,10]])

for i in range(1,6):
    imgData = cv2.imread(f"test_image/{i}.jpg")
    imgData = cv2.resize(imgData,(75,100)).reshape(1,100,75,3)
    preResult=myModel.predict(imgData)*arr
    print(preResult,np.argmax(preResult))

for i in range(7,15):
    imgData = cv2.imread(f"test_image/{i}.jpg")
    imgData = cv2.resize(imgData,(75,100)).reshape(1,100,75,3)
    preResult=myModel.predict(imgData)*arr
    print(preResult,np.argmax(preResult))


1/1 [==============================] - 0s 23ms/step
[[3.85985550e+02 9.99937654e+00 5.97321921e+02 4.83671068e-30]] 2
1/1 [==============================] - 0s 16ms/step
[[9.5142741  9.99998689 8.82311482 0.        ]] 1
1/1 [==============================] - 0s 18ms/step
[[3.04283778e+03 9.99515295e+00 4.53287358e+03 6.96565293e-34]] 2
1/1 [==============================] - 0s 15ms/step
[[7.08985681 9.99999046 6.53067359 0.        ]] 1
1/1 [==============================] - 0s 16ms/step
[[0.55493341 9.99999881 0.47809531 0.        ]] 1
1/1 [==============================] - 0s 17ms/step
[[347.14288631   9.99945641 492.69280303   0.        ]] 2
1/1 [==============================] - 0s 16ms/step
[[25.4133829   9.99996543 23.62335954  0.        ]] 0
1/1 [==============================] - 0s 16ms/step
[[1.41758341e+03 9.99785006e+00 1.83870043e+03 2.68366873e-37]] 2
1/1 [==============================] - 0s 17ms/step
[[4.36543341e+03 9.99297261e+00 6.68658001e+03 4.96899829e-34]] 2
1/1 [=